name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12.x', '14.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn build
